// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AkarIconsAir: typeof import('~icons/akar-icons/air')['default']
    AkarIconsSearch: typeof import('~icons/akar-icons/search')['default']
    AkarIconsTriangleDown: typeof import('~icons/akar-icons/triangle-down')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
